require 'dm-rails/middleware/identity_map'
class ApplicationController < ActionController::Base
  use Rails::DataMapper::Middleware::IdentityMap
  protect_from_forgery

  before_filter :load_alerts

  def load_alerts
   # @alerts = Alert.all
    @alerts = Alert.all(:show => true)
  end

  def render_404
    @title = "404 Page Not Found"
    render :template => "public/404.html.haml", :layout => false, :status => 404
  end

  Name_legend = { "uplc"=> "UPLC", "pressure_trace"=> "Pressure Trace", "chromatography"=>"Chromatography", "ms1"=>"MS1", "ms2"=>"MS2", "dynamic_sampling"=>"Dynamic Sampling", "ion_source"=>"Ion Source", "ion_treatment"=>"Ion Treatment", "peptide_ids"=> "Peptide IDs", "run_comparison"=>"Run Comparison", "id_charge_distributions_at_different_ms1max_quartiles_for_charges_1_4"=>"ID Charge Distributions At Different MS1max Quartiles For Charges 1-4", "precursor_m_z_averages_and_differences_from_1st_quartile_largest_of_different_ms1total_tic_quartiles_over_full_elution_period"=>"Precursor m/z Averages and Differences from 1st Quartile (Largest) of Different MS1Total (TIC) Quartiles Over Full Elution Period", 
      "number_of_compounds_in_common"=>"Number of Compounds in Common", "fraction_of_overlapping_compounds_relative_to_first_index"=>"Fraction of Overlapping Compounds - relative to first index", "fraction_of_overlapping_compounds_relative_to_second_index"=>"Fraction of Overlapping Compounds - relative to second index", "median_retention_rank_differences_for_compounds_in_common_percent"=>"Median Retention Rank Differences for Compounds in Common (Percent)", "avg_1_60_1_60"=>"Avg\t1.60\t1.60", 
      "average_retention_rank_differences_for_compounds_in_common_percent"=>"Average Retention Rank Differences for Compounds in Common (Percent)", "avg_2_30_2_30"=>"Avg\t2.30\t2.30", "number_of_matching_identified_ions_between_runs"=>"Number of Matching Identified Ions Between Runs", "relative_deviations_in_ms1_max_for_matching_identified_ions_between_runs"=>"Relative Deviations in MS1 Max For Matching Identified Ions Between Runs", "avg_1_00_1_00"=>"Avg\t1.00\t1.00", "relative_uncorrected_deviations_in_ms1_max_for_matching_identified_ions_between_runs"=>"Relative Uncorrected Deviations in MS1 Max For Matching Identified Ions Between Runs", "avg_0_00_0_00"=>"Avg\t0.00\t0.00", 
      "relative_corrected_deviations_in_ms1_max_for_matching_identified_ions_between_runs"=>"Relative Corrected Deviations in MS1 Max For Matching Identified Ions Between Runs", "relative_rt_trends_in_ms1_max_for_matching_identified_ions_between_runs"=>"Relative RT Trends in MS1 Max For Matching Identified Ions Between Runs", 
      "relative_rt_trends_corrected_deviations_of_ms1_max_for_matching_identified_ions_between_runs"=>"Relative RT Trends / Corrected Deviations of MS1 Max For Matching Identified Ions Between Runs", "median_relative_intensities_in_ms1_max_for_matching_identified_ions_between_runs"=>"Median Relative Intensities in MS1 Max For Matching Identified Ions Between Runs", "number_of_matching_doubly_charged_identified_ions_between_runs"=>"Number of Matching Doubly Charged Identified Ions Between Runs", 
      "relative_deviations_in_ms1_max_for_doubly_charged_matching_identified_ions_between_runs"=>"Relative Deviations in MS1 Max For Doubly Charged Matching Identified Ions Between Runs", "number_of_matching_triply_charged_identified_ions_between_runs"=>"Number of Matching Triply Charged Identified Ions Between Runs", "relative_deviations_in_ms1_max_for_triply_charged_matching_identified_ions_between_runs"=>"Relative Deviations in MS1 Max For Triply Charged Matching Identified Ions Between Runs", 
      "relative_2_deviations_in_ms1_max_for_matching_identified_ions_between_runs"=>"Relative 2 * Deviations in MS1 Max For Matching Identified Ions Between Runs", "relative_deviations_in_ms1_max_at_different_rt_quartiles_for_matching_identified_ions_between_runs_single_table"=>"Relative Deviations in MS1 Max at Different RT Quartiles For Matching Identified Ions Between Runs - Single Table", "relative_deviations_in_ms1_max_at_1_rt_quartile_for_matching_identified_ions_between_runs"=>"Relative Deviations in MS1 Max at 1 RT Quartile For Matching Identified Ions Between Runs", 
      "relative_deviations_in_ms1_max_at_2_rt_quartile_for_matching_identified_ions_between_runs"=>"Relative Deviations in MS1 Max at 2 RT Quartile For Matching Identified Ions Between Runs", "relative_deviations_in_ms1_max_at_3_rt_quartile_for_matching_identified_ions_between_runs"=>"Relative Deviations in MS1 Max at 3 RT Quartile For Matching Identified Ions Between Runs", "relative_deviations_in_ms1_max_at_4_rt_quartile_for_matching_identified_ions_between_runs"=>"Relative Deviations in MS1 Max at 4 RT Quartile For Matching Identified Ions Between Runs", "number_of_excess_early_eluting_identified_species"=>"Number of Excess Early Eluting Identified Species", 
      "number_of_excess_late_eluting_identified_species"=>"Number of Excess Late Eluting Identified Species", "peak_widths_at_half_max_at_rt_deciles"=>"Peak widths at half max at RT deciles", "rt_peptide_deciles"=>"RT peptide deciles", "oversampling_vs_rt"=>"Oversampling vs RT", "retention_time_decile_intervals"=>"Retention Time Decile Intervals", "matching_low_high_rt_peptide_ions"=>"Matching Low:High RT Peptide Ions", "rt_median_differences_for_matching_peptides"=>"RT Median Differences for Matching Peptides", "median_dev"=>"Median Dev", "median_skew"=>"Median Skew", "fraction_of_1_rt_decile_peps_in_common"=>"Fraction of 1 RT Decile Peps In Common", 
      "fraction_of_2_rt_decile_peps_in_common"=>"Fraction of 2 RT Decile Peps In Common", "fraction_of_3_rt_decile_peps_in_common"=>"Fraction of 3 RT Decile Peps In Common", "fraction_of_4_rt_decile_peps_in_common"=>"Fraction of 4 RT Decile Peps In Common", "fraction_of_5_rt_decile_peps_in_common"=>"Fraction of 5 RT Decile Peps In Common", "fraction_of_6_rt_decile_peps_in_common"=>"Fraction of 6 RT Decile Peps In Common", "fraction_of_7_rt_decile_peps_in_common"=>"Fraction of 7 RT Decile Peps In Common", "fraction_of_8_rt_decile_peps_in_common"=>"Fraction of 8 RT Decile Peps In Common", "fraction_of_9_rt_decile_peps_in_common"=>"Fraction of 9 RT Decile Peps In Common", 
      "fraction_of_10_rt_decile_peps_in_common"=>"Fraction of 10 RT Decile Peps In Common", "end_interrun_and_decile_results"=>"End Interrun and Decile Results", "ab_deviation_vs_difference_in_run_order"=>"Ab Deviation vs Difference in Run Order - ", "median_rt_rank_vs_difference_in_run_order"=>"Median RT Rank vs Difference in Run Order", "begin_runseries_results"=>"Begin Runseries Results", "begin_series_1"=>"Begin Series=1", "files_analyzed_2"=>"Files Analyzed (2)", "run_number_1_2"=>"Run Number\t1\t2\t", "spectrum_counts"=>"Spectrum Counts", "first_and_last_ms1_rt_min"=>"First and Last MS1 RT (min)", "tryptic_peptide_counts"=>"Tryptic Peptide Counts", 
      "peptide_counts"=>"Peptide Counts", "middle_peptide_retention_time_period_min"=>"Middle Peptide Retention Time Period (min)", "ms1_during_middle_and_early_peptide_retention_period"=>"MS1 During Middle (and Early) Peptide Retention Period", "ms1_total_ion_current_for_different_rt_periods"=>"MS1 Total Ion Current For Different RT Periods", "total_ion_current_for_ids_at_peak_maxima"=>"Total Ion Current For IDs at Peak Maxima", "precursor_m_z_for_ids"=>"Precursor m/z for IDs", "number_of_ions_vs_charge"=>"Number of Ions vs Charge", "averages_vs_rt_for_ided_peptides"=>"Averages vs RT for IDed Peptides", "precursor_m_z_peptide_ion_m_z_2_charge_only_reject_0_45_m_z"=>"Precursor m/z - Peptide Ion m/z (+2 Charge Only, Reject >0.45 m/z)", 
      "ion_ids_by_charge_state_relative_to_2"=>"Ion IDs by Charge State (Relative to +2)", "average_peptide_lengths_for_different_charge_states"=>"Average Peptide Lengths for Different Charge States", "average_peptide_lengths_for_charge_2_for_different_numbers_of_mobile_protons"=>"Average Peptide Lengths For Charge 2 for Different Numbers of Mobile Protons", "numbers_of_ion_ids_at_different_charges_with_1_mobile_proton"=>"Numbers of Ion Ids at Different Charges with 1 Mobile Proton", 
      "percent_of_ids_at_different_charges_and_mobile_protons_relative_to_ids_with_1_mobile_proton"=>"Percent of IDs at Different Charges and Mobile Protons Relative to IDs with 1 Mobile Proton", "precursor_m_z_monoisotope_exact_m_z"=>"Precursor m/z - Monoisotope Exact m/z", "ms2_id_spectra"=>"MS2 ID Spectra", "ms1_id_max"=>"MS1 ID Max", "ms1_id_abund_at_ms2_acquisition"=>"MS1 ID Abund at MS2 Acquisition", "ms2_id_abund_reported"=>"MS2 ID Abund Reported", 
      "max_peak_width_for_ids_sec"=>"Max Peak Width for IDs (sec)", "peak_width_at_half_height_for_ids"=>"Peak Width at Half Height for IDs", "peak_widths_at_half_max_over_rt_deciles_for_ids"=>"Peak Widths at Half Max over RT deciles for IDs", "nearby_resampling_of_ids_oversampling_details"=>"Nearby Resampling of IDs - Oversampling Details", "wide_rt_differences_for_ids_4_min"=>"Wide RT Differences for IDs (> 4 min)", 
      "fraction_of_repeat_peptide_ids_with_divergent_rt_rt_vs_rt_best_id_chromatographic_bleed"=>"Fraction of Repeat Peptide IDs with Divergent RT (RT vs RT-best ID) - Chromatographic 'Bleed'", "early_and_late_rt_oversampling_spectrum_ids_unique_peptide_ids_chromatographic_flow_through_bleed"=>"Early and Late RT Oversampling (Spectrum IDs/Unique Peptide IDs) - Chromatographic: Flow Through/Bleed", 
      "peptide_ion_ids_by_3_spectra_hi_vs_1_3_spectra_lo_extreme_oversampling"=>"Peptide Ion IDs by > 3 Spectra (Hi) vs  1-3 Spectra (Lo) - Extreme Oversampling", "ratios_of_peptide_ions_ided_by_different_numbers_of_spectra_oversampling_measure"=>"Ratios of Peptide Ions IDed by Different Numbers of Spectra - Oversampling Measure", 
      "single_spectrum_peptide_ion_identifications_oversampling_measure"=>"Single Spectrum Peptide Ion Identifications - Oversampling Measure", "ms1max_ms1sampled_abundance_ratio_ids_inefficient_sampling"=>"MS1max/MS1sampled Abundance Ratio IDs - Inefficient Sampling", "rt_ms1max_rt_ms2_for_ids_sec"=>"RT(MS1max)-RT(MS2) for IDs (sec) ", 
      "ion_injection_times_for_ids_ms"=>"Ion Injection Times for IDs (ms)", "relative_fraction_of_peptides_in_retention_decile_matching_a_peptide_in_other_runs"=>"Relative Fraction of Peptides in Retention Decile Matching a Peptide in Other Runs", "relative_uniqueness_of_peptides_in_decile_found_anywhere_in_other_runs"=>"Relative Uniqueness of Peptides in Decile Found Anywhere in Other Runs", "differences_in_elution_rank_percent_of_matching_peptides_in_other_runs"=>"Differences in Elution Rank (Percent) of Matching Peptides in Other Runs", "median_ratios_of_ms1_intensities_of_matching_peptides_in_other_runs"=>"Median Ratios of MS1 Intensities of Matching Peptides in Other Runs", 
      "uncorrected_and_rt_corrected_relative_intensities_of_matching_peptides_in_other_runs"=>"Uncorrected and RT Corrected Relative Intensities of Matching Peptides in Other Runs", "magnitude_of_rt_correction_of_intensities_of_matching_peptides_in_other_runs"=>"Magnitude of RT Correction of Intensities of Matching Peptides in Other Runs", "top_ion_abundance_measures"=>"Top Ion Abundance Measures", "end_series_1"=>"End Series=1", "end_runseries_results"=>"End Runseries Results", "precursor_m_z_averages_at_different_ms1total_tic_quartiles_over_middle_elution_period"=>"Precursor m/z Averages at Different MS1Total (TIC) Quartiles Over Middle Elution Period", "run_q1_precursor_m_z_q2_q1_q3_q1_q4_q1_q1_tic_1000_q2_q1_q3_q1_q4_q1"=>"Run #, Q1 precursor m/z, Q2-Q1, Q3-Q1, Q4-Q1, Q1 TIC/1000, Q2/Q1, Q3/Q1, Q4/Q1", "_1"=>"1", "_2"=>"2", ""=>"", "decile"=>"Decile", 
      "run_1"=>"Run 1", "run_2"=>"Run 2", "run"=>"Run", "median"=>"Median  ", "avg"=>"Avg", "lab_1"=>"Lab 1", "avgdel"=>"AvgDel", "meddel"=>"MedDel", "diff1"=>"Diff1", "ms2_scans"=>"MS2 scans", "ms1_scans_full"=>"MS1 Scans/Full", "ms1_scans_other"=>"MS1 Scans/Other", "first_ms1"=>"First MS1", "last_ms1"=>"Last MS1 ", "peptides"=>"Peptides", "ions"=>"Ions    ", "identifications"=>"Identifications", "abundance_pct"=>"Abundance Pct", "abundance_1000"=>"Abundance/1000", "ions_peptide"=>"Ions/Peptide", "ids_peptide"=>"IDs/Peptide", "semi_tryp_peps"=>"Semi/Tryp Peps", "semi_tryp_cnts"=>"Semi/Tryp Cnts", "semi_tryp_abund"=>"Semi/Tryp Abund", "miss_tryp_peps"=>"Miss/Tryp Peps", "miss_tryp_cnts"=>"Miss/Tryp Cnts", "miss_tryp_abund"=>"Miss/Tryp Abund", "net_oversample"=>"Net Oversample", "half_period"=>"Half Period", 
      "start_time"=>"Start Time", "mid_time"=>"Mid Time", "qratio_time"=>"Qratio Time", "ms1_scans"=>"MS1 Scans", "pep_id_rate"=>"Pep ID Rate", "id_rate"=>"ID Rate ", "id_efficiency"=>"ID Efficiency", "s_n_median"=>"S/N Median", "tic_median_1000"=>"TIC Median/1000", 
      "npeaks_median"=>"NPeaks Median", "scan_to_scan"=>"Scan-to-Scan", "s2s_3q_med"=>"S2S-3Q/Med", "s2s_1qrt_med"=>"S2S-1Qrt/Med", "s2s_2qrt_med"=>"S2S-2Qrt/Med", "s2s_3qrt_med"=>"S2S-3Qrt/Med", "s2s_4qrt_med"=>"S2S-4Qrt/Med", "esi_off_middle"=>"ESI Off Middle", 
      "esi_off_early"=>"ESI Off Early", "max_ms1_jump"=>"Max MS1 Jump", "max_ms1_fall"=>"Max MS1 Fall", "ms1_jumps_10x"=>"MS1 Jumps >10x", "ms1_falls_10x"=>"MS1 Falls >10x", "_1st_quart_id"=>"1st Quart ID", "middle_id"=>"Middle ID", "last_id_quart"=>"Last ID Quart", "to_end_of_run"=>"To End of Run", "med_tic_id_1000"=>"Med TIC ID/1000", 
      "interq_tic"=>"InterQ TIC", "mid_interq_tic"=>"Mid InterQ TIC", "half_width"=>"Half Width", "quart_ratio"=>"Quart Ratio", "precursor_min"=>"Precursor Min", "precursor_max"=>"Precursor Max", "med_q1_tic"=>"Med @ Q1 TIC", "med_q4_tic"=>"Med @ Q4 TIC", "med_q1_rt"=>"Med @ Q1 RT", "med_q4_rt"=>"Med @ Q4 RT", "med_charge_1"=>"Med Charge +1", 
      "med_charge_2"=>"Med Charge +2", "med_charge_3"=>"Med Charge +3", "med_charge_4"=>"Med Charge +4", "charge_1"=>"Charge +1", "charge_2"=>"Charge +2", "charge_3"=>"Charge +3", "charge_4"=>"Charge +4", "charge_5"=>"Charge +5", "length_q1"=>"Length Q1", "length_q4"=>"Length Q4", "charge_q1"=>"Charge Q1", "charge_q4"=>"Charge Q4", "spectra"=>"Spectra ", 
      "mean_absolute"=>"Mean Absolute", "ppm_median"=>"ppm Median", "ppm_interq"=>"ppm InterQ", "_2_ion_count"=>"+2 Ion Count", "naa_ch_2_mp_1"=>"NAA,Ch=2,MP=1", "naa_ch_2_mp_0"=>"NAA,Ch=2,MP=0", "naa_ch_2_mp_2"=>"NAA,Ch=2,MP=2", "ch_1_mp_1"=>"Ch=1 MP=1", 
      "ch_2_mp_1"=>"Ch=2 MP=1", "ch_3_mp_1"=>"Ch=3 MP=1", "ch_4_mp_1"=>"Ch=4 MP=1", "ch_1_mp_0"=>"Ch=1 MP=0", "ch_2_mp_0"=>"Ch=2 MP=0", "ch_3_mp_0"=>"Ch=3 MP=0", "more_than_100"=>"More Than 100", "betw_100_0_50_0"=>"Betw 100.0-50.0", "betw_50_0_25_0"=>"Betw 50.0-25.0", "betw_25_0_12_5"=>"Betw 25.0-12.5", "betw_12_5_6_3"=>"Betw 12.5-6.3", 
      "betw_6_3_3_1"=>"Betw 6.3-3.1", "betw_3_1_1_6"=>"Betw 3.1-1.6", "betw_1_6_0_8"=>"Betw 1.6-0.8", "top_half"=>"Top Half", "next_half_2"=>"Next Half (2)", "next_half_3"=>"Next Half (3)", "next_half_4"=>"Next Half (4)", "next_half_5"=>"Next Half (5)", "next_half_6"=>"Next Half (6)", "next_half_7"=>"Next Half (7)", "next_half_8"=>"Next Half (8)", 
      "npeaks_interq"=>"NPeaks InterQ", "s_n_interq"=>"S/N InterQ", "id_score_median"=>"ID Score Median", "id_score_interq"=>"ID Score InterQ", "idsc_med_q1msmx"=>"IDSc Med Q1Msmx", "median_midrt"=>"Median MidRT", "_75_25_midrt"=>"75/25 MidRT", "_95_5_midrt"=>"95/5 MidRT", "_75_25_pctile"=>"75/25 Pctile", "_95_5_pctile"=>"95/5 Pctile", 
      "median_value"=>"Median Value", "third_quart"=>"Third Quart", "last_decile"=>"Last Decile", "med_top_quart"=>"Med Top Quart", 
      "med_top_16th"=>"Med Top 16th", "med_top_100"=>"Med Top 100", "median_disper"=>"Median Disper", "med_quart_disp"=>"Med Quart Disp", "med_16th_disp"=>"Med 16th Disp", "med_100_disp"=>"Med 100 Disp", "_3quart_value"=>"3Quart Value", "_9dec_value"=>"9Dec Value", "ms1_interscan_s"=>"MS1 Interscan/s", "ms1_scan_fwhm"=>"MS1 Scan/FWHM", 
      "ids_used"=>"IDs Used  ", "first_decile"=>"First Decile", "repeated_ids"=>"Repeated IDs", "med_rt_diff_s"=>"Med RT Diff/s", "_1q_rt_diff_s"=>"1Q RT Diff/s", 
      "_1dec_rt_diff_s"=>"1Dec RT Diff/s", "median_dm_z"=>"Median dm/z", "quart_dm_z"=>"Quart dm/z", "_4_min"=>"+ 4 min      ", "pep_ions_hi"=>"Pep Ions (Hi)", 
      "ratio_hi_lo"=>"Ratio Hi/Lo", "spec_cnts_hi"=>"Spec Cnts (Hi)", "spec_pep_hi"=>"Spec/Pep (Hi)", "spec_cnt_excess"=>"Spec Cnt Excess", "once_twice"=>"Once/Twice", 
      "twice_thrice"=>"Twice/Thrice", "peptide_ions"=>"Peptide Ions", "fract_1_ions"=>"Fract >1 Ions", "_1_vs_1_pepion"=>"1 vs >1 PepIon", "_1_vs_1_spec"=>"1 vs >1 Spec", 
      "median_all_ids"=>"Median All IDs", "_3q_all_ids"=>"3Q All IDs", "_9dec_all_ids"=>"9Dec All IDs", "med_top_dec"=>"Med Top Dec", "med_bottom_1_2"=>"Med Bottom 1/2", 
      "med_diff_abs"=>"Med Diff Abs", "median_diff"=>"Median Diff", "first_quart"=>"First Quart", "ms1_median"=>"MS1 Median", "ms1_maximum"=>"MS1 Maximum", 
      "ms2_median"=>"MS2 Median", "ms2_maximun"=>"MS2 Maximun", "ms2_fract_max"=>"MS2 Fract Max", "all_deciles"=>"All Deciles", "comp_to_first"=>"Comp to First", 
      "comp_to_last"=>"Comp to Last", "average_diff"=>"Average Diff", "median_2_diff"=>"Median*2 Diff", "comp_to_first_2"=>"Comp to First*2", "comp_to_last_2"=>"Comp to Last*2", "uncor_rel_first"=>"Uncor rel First", "uncor_rel_last"=>"Uncor rel Last", 
      "corr_rel_first"=>"Corr rel First", "corr_rel_last"=>"Corr rel Last", "top_10_abund"=>"Top 10% Abund", "top_25_abund"=>"Top 25% Abund", "top_50_abund"=>"Top 50% Abund", "fractab_top"=>"Fractab Top", "fractab_top_10"=>"Fractab Top 10", "fractab_top_100"=>"Fractab Top 100"}
      


end
